### PR TITLE
Migrate content from archive.enroute to bndtools

### PR DESCRIPTION
**Pull request by chrisrueger**
Based on https://bnd.discourse.group/t/which-content-to-move-from-v2archive-enroute-osgi-org-to-bndtools-org/432

### CODE REVIEW

**Comment by chrisrueger** [comment]
Hi @pkriens, this is a first draft of migrating content from archive.enroute to bndtools.org:

- I added a new section "Knowledge" to the sidebar (not sure, as it becomes larger... suggestions welcome)
- made the sidebar dynamic via `sidebar.yml` (similar to bnd manual) which allows to show active top-level link 
- added a sublayout `prev-next-collection.html` for collection pages which display `prev/next` links (e.g. services).

image

**Comment by chrisrueger** [comment]
Ok sounds fine to me. I will do a quick review later of the stuff from the weekend and merge then.

**Comment by pkriens** [comment]
You're ok to set a meeting for an hour each week? To keep the spirit burning? Preferences? We can do it around the bnd call but I think we need to do it weekly.

**Comment by chrisrueger** [comment]
> You're ok to set a meeting for an hour each week? To keep the spirit burning? Preferences? We can do it around the bnd call but I think we need to do it weekly.

Yes, let's coordinate via slack. 
I am going to merge now.

I will ping you on slack.

**Comment by chrisrueger** [comment]
@pkriens before I merge: How do you merge usually?

image

**Comment by chrisrueger** [comment]
@pkriens ok I merged via rebase. I thought in this case keeping commits might be helpful in this case. I pinged you in slack.

**Comment by peterkir** [comment]
I would like to join forces. How can I contribute to the work?

**Comment by pkriens** [comment]
Send me your email and I'll invite you to the slack.

We need to review a lot of stuff. Could really use some help reviewing and updating the tutorials.

**Pull request merged**
