### PR TITLE
Documentation additions for next 7.1

### PR DESCRIPTION
**Pull request by chrisrueger**
This PR intends to add new documentation relevant website content for the next release e.g. 

- Java OSGi Service Wizard https://github.com/bndtools/bnd/issues/5632#issuecomment-1851175575
- TODO Resolution View
- TODO other PRs e.g. https://github.com/bndtools/bnd/pulls?q=is%3Apr+is%3Aclosed+author%3Achrisrueger

## Java OSGi Service Wizard

- added a new "Project Templates" Sidebar entry

image

image

### CODE REVIEW

**Comment by scottslewis** [comment]
Hi @chrisrueger 

Although I hightly appreciate your effort here, I would recommend leaving out the 'Custom OSGi Service Wizards' section if the release of bndtools is imminent (within next month say).   The example I provided and that you put in is really minimal and doesn't really provide enough information on how to use the new wizard extension point (along with the associated bndtools template),   

I just provided it to explain to you and other bndtools developers what was now possible.   I will commit to producing more detailed documentation with full examples (maybe a tutorial) about this for a future release, but I feel that the amount of docs available right now for the Custom OSGi Service wizard extensions is less helpful that it should/must be/currently for other bndtools devs to actually use.

**Comment by chrisrueger** [comment]
@scottslewis you mean leaving out [this commit ](https://github.com/bndtools/bndtools.github.io/pull/146/commits/25632e31a6e987caf17eac2628975ac20f5efdf5) for there Developer Guide? 

Sure no problem. I will revert it.

**Comment by scottslewis** [comment]
> @scottslewis you mean leaving out [this commit ](https://github.com/bndtools/bndtools.github.io/pull/146/commits/25632e31a6e987caf17eac2628975ac20f5efdf5) for there Developer Guide?

Yeah.   I promise to produce a full explanation of the use of the new wizard extension point with the bndtools service templating capability, but I can't right away.

> 
> Sure no problem. I will revert it.

Thanks.

**Comment by chrisrueger** [comment]
@pkriens I think I am ready. 
I added the "since: 7.1.0" variable to markdown header and show it at the top of the page (What we discussed in the call today)

image

I think this one can be merged.

**Pull request merged**
